apiVersion: v1
kind: Service
metadata:
  name: wil42
  labels:
    app: wil42
spec:
  type: NodePort 
  ports:
  - name: http
    port: 80
    targetPort: 8888
  selector:
    app: wil42
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42
spec:
  selector:
    matchLabels:
      app: wil42
  replicas: 1
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
      - name: wil42
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
